version: '3.8'

services:
  app:
    build:
      context: .              # Dockerfile 现在在根目录
      dockerfile: Dockerfile  # 可省略，默认就是这个名字
    image: likanug515/free-v2ray      # ⬅️ 指定构建后的镜像名和版本
    container_name: free-v2ray
    working_dir: /app
    command: python main.py
    volumes:
      - ./v2ray:/app/v2ray  # ⬅️ 挂载当前目录到容器的 /app/v2ray 目录
      - ./logs:/app/logs  # ⬅️ 挂载日志目录
      - ./conf:/app/conf  # ⬅️ 挂载配置目录
    environment:
      - PYTHONUNBUFFERED=1